### ISSUE TITLE
How to use open in Typescript.

### ISSUE THREAD

**Issue by baardl** [sindresorhus/open#124]
Hi.
I try to use **open** from a Typescript project. 

* My import is
```
yarn add open
yarn add @types/open
```

* My code is 
```
import {Command, flags} from "@oclif/command"
import open from "open"

export default class Open extends Command {
  static description = "Open an webpage"

  static examples = [
    `$ transcribe open -a link_to_azure_ad
`,
  ]
  static flags = {
    help: flags.help({char: "h"}),
    // flag with a value (-n, --name=VALUE)
    adUri: flags.string({char: "a", description: "Azure Ad link to use for login"}),
  }

  async run() {
    const {flags} = this.parse(Open)

    const adUri = flags.adUri
    if (flags.adUri) {
      this.log(`open ${adUri} `)
      await open("unicorn.png", {wait: true})
      this.log("The image viewer app closed")

      // Opens the url in the default browser
      await open("https://sindresorhus.com")

      // Specify the app to open in
      await open("https://sindresorhus.com", {app: "firefox"})

      // Specify app arguments
      await open("https://sindresorhus.com", {app: ["google chrome", "--incognito"]})
    } else {
      this.log("Missing required parameter -a link_to_azure_ad")
    }
  }
}
```

* The error I get is
```
transcribe open -a https://www.nrk.no
open https://www.nrk.no 
TypeError: open_1.default is not a function
    at Open.run (.../transcriber-cli/src/commands/open.ts:23:17)
    at Open._run (..../transcriber-cli/node_modules/@oclif/command/lib/command.js:34:31)
```

Hope you may suggest what I´m doing wrong, thanks.
Bård

**Comment by sindresorhus** [comment]
This is a CommonJS module, you either need to import it using `import open = require('open');` or use these settings in your tsconfig: https://github.com/sindresorhus/tsconfig/blob/d4a760348b9c1e3f3acfd4f351484583ce498c06/tsconfig.json#L9-L10

**Comment by baardl** [comment]
Thank you, Sindre.
"esModuleInterop" from tsconfig.json did work :-)
