### ISSUE TITLE
error: `xdg-open:line500: gnome-open：cannot find command` in Manjaro-gnome 64bit

### ISSUE THREAD

**Issue by nocsg** [sindresorhus/open#283]
My gnome version is 41.3 and I can use the command 'xdg-open' but cannot user `gnome-open` or `gvfs-open` in my termianl. In GNOME itself `gnome-open` [has been replaced](https://askubuntu.com/questions/101965/what-is-the-replacement-for-gnome-open-in-gnome) by `gvfs-open`.
```
post/node_modules/open-browser-webpack-plugin/index.js:46
        if (err) throw err;
                 ^

Error: Command failed: /post/node_modules/open/vendor/xdg-open "http://localhost:23333"
/post/node_modules/open/vendor/xdg-open:line500: gnome-open：cannot find command

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) {
  killed: false,
  code: 4,
  signal: null,
```

**Comment by sindresorhus** [comment]
This package uses but does not maintain `xdg-open`. You'll need to report the issue over at https://gitlab.freedesktop.org/xdg/xdg-utils
